export enum UserRole {
  MEMBER = "MEMBER",
  CREATOR = "CREATOR",
  ADMIN = "ADMIN",
}

export enum InstrumentEnum {
  CASH_EQUITY = "CASH_EQUITY",
  STOCK_FUTURES = "STOCK_FUTURES",
  STOCK_OPTIONS = "STOCK_OPTIONS",
  INDEX_FUTURES = "INDEX_FUTURES",
  INDEX_OPTIONS = "INDEX_OPTIONS",
  COMMODITIES = "COMMODITIES",
  CURRENCY_DERIVATIVES = "CURRENCY_DERIVATIVES",
}

export enum StrategyEnum {
  INTRADAY = "INTRADAY",
  SWING = "SWING",
  POSITIONAL = "POSITIONAL",
  OPTIONS_SELLING = "OPTIONS_SELLING",
  OPTIONS_BUYING = "OPTIONS_BUYING",
  SCALPING = "SCALPING",
  TREND_FOLLOWING = "TREND_FOLLOWING",
  MEAN_REVERSION = "MEAN_REVERSION",
  EVENT_BASED = "EVENT_BASED",
}

export enum RiskProfileEnum {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
}

export enum CapitalRequiredBucketEnum {
  SMALL = "SMALL",
  MEDIUM = "MEDIUM",
  LARGE = "LARGE",
}

export enum KycStatusEnum {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum SebiStatusEnum {
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
}
